repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.0
    hooks:
      - id: pip-compile
        name: pip-compile setup.py
        args:
          - --allow-unsafe
          - --generate-hashes
          - --reuse-hashes
        files: ^(setup\.py|requirements\.txt)$
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args:
          - --allow-unsafe
          - --generate-hashes
          - --reuse-hashes
          - requirements-dev.in
        files: ^requirements-dev\.(in|txt)$
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.4
    hooks:
      - id: pylint
        additional_dependencies:
        - adafruit-circuitpython-gps
        - piexif
        - pyserial
        - pytest
