= Detectionator
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
:keywords: camera detect detection gps object opencv photo pi picamera picamera2 python raspberry tensorflow
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:AutoUpload: https://github.com/jwillikers/autoupload[AutoUpload]
:Exif: https://en.wikipedia.org/wiki/Exif[Exif]
:Immich: https://immich.app/[Immich]
:Immich-CLI: https://immich.app/docs/features/command-line-interface/[Immich CLI]
:just: https://github.com/casey/just[just]
:MinIO: https://min.io/[MinIO]
:picamera2: https://github.com/raspberrypi/picamera2[picamera2]
:pip-tools: https://github.com/jazzband/pip-tools[pip-tools]
:pySerial: https://github.com/pyserial/pyserial[pySerial]
:Rclone: https://rclone.org/[Rclone]
:systemd: https://systemd.io/[systemd]

image:https://github.com/jwillikers/detectionator/actions/workflows/test.yaml/badge.svg[Tests, link=https://github.com/jwillikers/detectionator/actions/workflows/test.yaml]
image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]
image:https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/astral-sh/ruff/main/assets/badge/v2.json[Ruff, link=https://github.com/astral-sh/ruff]

A Raspberry Pi camera for taking pictures using object detection.

== Overview

The Detectionator is a fairly minimal Raspberry Pi camera build for taking pictures of particular objects like animals or people.
The Detectionator incorporates {Exif} geolocation metadata in the photographs it takes.
With the help of my {AutoUpload} project, pictures are automatically offloaded from the local storage to cloud-based storage such as S3-compatible object storage with {Rclone} or to {Immich} with the {Immich-CLI}.
The photos are then removed from local storage.
This repository contains documentation, configuration files, and the Python program for the Detectionator.
The project is largely based off of the tensorflow example in the {picamera2} project and includes the same models.

== Components

The Detectionator is based off of the Raspberry Pi 5 and the Camera Module 3.
It incorporates a GPS HAT for the Raspberry Pi to obtain the geolocation data to embed in the photographs.

[NOTE]
====
The GPS HAT requires soldering on a GPIO header.
====

.Detectionator Components
* https://www.raspberrypi.com/products/raspberry-pi-5-model-b/[Raspberry Pi 5 Model B] (4 GB RAM or better)
* https://www.raspberrypi.com/products/camera-module-3/[Raspberry Pi Camera Module 3]
* https://www.adafruit.com/product/1646[100mm Flex Cable for Raspberry Pi Camera]
* https://www.arducam.com/product/white-camera-enclosure-case-pi-cameras/[Camera Enclosure Case for Raspberry Pi Camera Module 3/V1/V2 and Arducam 16MP/64MP Camera]
// todo I might switch to the HAT and use gpsd instead: https://www.adafruit.com/product/2324
* https://www.adafruit.com/product/4279[Adafruit Ultimate GPS GNSS with USB - 99 channel w/10 Hz updates]
* https://www.adafruit.com/product/2324[Adafruit Ultimate GPS HAT for Raspberry Pi]
* A CR1220 Battery for the RTC.
* https://shop.pimoroni.com/products/nvme-base?variant=41219587178579[NVMe Base for Raspberry Pi 5].
* A sufficiently large and performant M.2 NVMe SSD.
I prefer the SK hynix Gold P31 for lower-power and heat situations.
* Alternatively, a sufficiently large and performant microSD card can be used instead of NVMe storage.
The https://www.samsung.com/us/computing/memory-storage/memory-cards/pro-ultimate-adapter-microsdxc-128gb-mb-my128sa-am/[128GB Samsung Pro Ultimate] and https://www.samsung.com/us/computing/memory-storage/memory-cards/pro-endurance-adapter-microsdxc-128gb-mb-mj128ka-am/[128GB Samsung Pro Endurance] are two good options.
* A USB-C to USB-A cable to connect the Adafruit Ultimate GPS with USB to the Pi.
* A USB-C power supply for powering the Pi.
* A fan or case with a fan to keep the Raspberry Pi 5 cool.

[TIP]
====
The Adafruit Ultimate GPS HAT's cutout for the camera flex cable doesn't line up with the connectors on the Raspberry Pi 5.
Use a drill to widen the cutout towards the edge of the board to allow the flex cable enough room to fit.
====

== Install

. Install the 64-bit full version of https://www.raspberrypi.com/software/[Raspberry Pi OS] to a microSD card.
The configuration files assume the primary user is `core`, which can be configured when using Raspberry Pi Imager to write the image.
This project has been tested with Raspberry Pi OS 5 based on Debian Bookworm.
. Insert the microSD card into the Raspberry Pi.
. Boot the Raspberry Pi.
. Follow the instructions to configure the storage service and autoupload {systemd} units in the {AutoUpload} README.
. Create `detectionator` user account.
// todo
. Install {just} by following the instructions in the https://github.com/casey/just?tab=readme-ov-file#installation[installation section].
This will automatically upload photos in the `~/Pictures` directory.
The commands to enable the units should look similar to the following.
Use the _user_ unit, for Immich.
+
Immich::
+
[,sh]
----
systemctl --user enable --now autoupload-immich@$(systemd-escape --path ~/Pictures).path
----

Rclone::
+
[,sh]
----
sudo systemctl enable --now autoupload-rclone@$(systemd-escape --path ~/Pictures).path
----

. For security, be sure to disable password-based SSH authentication.
After your public key has been added to the `~/.ssh/authorized_keys` file on the Pi Camera, this can be configured in the `/etc/ssh/sshd_config` file.
You can follow the instructions in my https://github.com/jwillikers/openssh-config[OpenSSH Config] repository to accomplish this and a few other optimizations.

. Update the package lists.
+
[,sh]
----
sudo apt-get update
----

. Upgrade everything.
+
[,sh]
----
sudo apt-get --yes full-upgrade
----

. Make the `~/Projects` directory.
+
[,sh]
----
mkdir --parents ~/Projects
----

. Clone this project's repository to the `~/Projects` directory.
+
[,sh]
----
git -C ~/Projects clone https://github.com/jwillikers/detectionator.git
----

. Change to the project's directory.
+
[,sh]
----
cd ~/Projects/detectionator
----

. Set up the environment with `just init`.
This will install dependencies and initialize the virtual environment.
It also installs a special udev rule for the Adafruit Ultimate GPS to give it a static device name.
+
[,sh]
----
just init
----

. Enable the serial port hardware and better PCIe speeds in `config.txt`.
+
./boot/firmware/config.txt
[,ini]
----
[all]
dtparam=pciex1_gen=3
dtoverlay=pps-gpio,gpiopin=4
dtparam=uart0=on
----

// todo eeprom config
// UART_BAUD=9600

. Ensure that `console=tty1` is in `/boot/firmware/cmdline.txt` and not `console=ttyAMA0` or `console=serial0`.
+
./boot/firmware/cmdline.txt
[source]
----
console=tty1 root=PARTUUID=c64d4099-02 rootfstype=ext4 fsck.repair=yes rootwait cfg80211.ieee80211_regdom=US
----

. Configure the `pps-gpio` module to be loaded.
+
[,sh]
----
echo 'pps-gpio' | sudo tee /etc/modules-load.d/pps-gpio.conf
----

. Configure gpsd to use the GPS HAT.
The serial port `ttyAMA0` is used and since the Raspberry Pi 5 has a built-in RTC, `pps1` is used instead of `pps0` here.
+
./etc/default/gpsd
[,ini]
----
# Devices gpsd should collect to at boot time.
# They need to be read/writeable, either by user gpsd or the group dialout.
DEVICES="/dev/ttyAMA0 /dev/pps1"

# Other options you want to pass to gpsd
GPSD_OPTIONS="-n"

# Automatically hot add/remove USB GPS devices via gpsdctl
USBAUTO="true"
----

. Configure chrony to use the GPS HAT for time.
+
./etc/chrony/conf.d/gpsd.conf
[source]
----
# set larger delay to allow the NMEA source to overlap with
# the other sources and avoid the falseticker status
refclock SOCK /run/chrony.ttyAMA10.sock refid GPS precision 1e-1 offset 0.9999
refclock SOCK /run/chrony.pps1.sock refid PPS precision 1e-7
----

. Reboot for the new udev rules to take effect.
+
[,sh]
----
sudo systemctl reboot
----

. Use `just run` to run the `detectionator.py` Python script inside the virtual environment.
+
[,sh]
----
just run
----

. Install and activate the systemd service with `just install`.
+
[,sh]
----
just install
----

[TIP]
====
Send the application the `SIGUSR1` signal to capture sample photographs for both the high and low resolution modes.

[,sh]
----
kill --signal SIGUSR1 $(pgrep python)
----
====

== HDR

The Raspberry Pi Camera Module 3 supports HDR, but only at a lower resolution.
HDR support has to toggled when `detectionator.py` isn't running.

. Show the available V4L subdevices.
+
[,sh]
----
ls /dev/v4l-subdev*
/dev/v4l-subdev0  /dev/v4l-subdev1  /dev/v4l-subdev2  /dev/v4l-subdev3
----

. To enable HDR support for the Raspberry Pi Camera Module 3, use the following command on one of the V4L subdevices.
In my case, this ended up being `/dev/v4l-subdev2`.
+
[,sh]
----
just hdr /dev/v4l-subdev2
----

. To disable HDR support for the Raspberry Pi Camera Module 3, use this command with the corresponding V4L subdevice.
+
[,sh]
----
just hdr /dev/v4l-subdev2 disable
----

== Development

. Run `just init-dev` to initialize the virtual environment for development.
This will install all of the necessary dependencies and the {pre-commit} hooks.
+
[,sh]
----
just init-dev
----

. Run the tests with https://docs.pytest.org/en/latest/[pytest] by running `just test`.
+
[,sh]
----
just test
----

. To update dependencies, run `just update`.
+
[,sh]
----
just update
----

. Use `just --list` to list other available tasks.
+
[,sh]
----
just --list
----

== todo

- [x] Use https://gpsd.gitlab.io/gpsd/gpsd-time-service-howto.html[gpsd].
- [] Create classes for different data types to better organize things.
- [x] Cache the GPS data to reduce the time to capture pictures between detections?
Use TTLCache from https://github.com/tkem/cachetools/[cachetools].
- [x] Add support for a TOML config file with https://github.com/bw2/ConfigArgParse[ConfigArgParse].
- [] async
- [] Switch from picamera2 to gstreamer to work with more hardware.
- [] mypy
- [] Create a weatherproof enclosure for the camera.
- [] Add a NixOS configuration and build SD card images.

== See Also

* https://docs.circuitpython.org/projects/gps/en/latest/[Adafruit GPS Library Documentation]
* https://learn.adafruit.com/adafruit-ultimate-gps-hat-for-raspberry-pi[Adafruit Ultimate GPS HAT for Raspberry Pi Documentation]
* https://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf[Exchangeable image file format for digital still cameras Exif Version 2.3]
* https://pyserial.readthedocs.io/en/latest/index.html[pySerial Documentation]
* https://www.raspberrypi.com/news/using-the-picamera2-library-with-tensorflow-lite/[Using the Picamera2 library with TensorFlow Lite]

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[Code of Conduct] file.

== License

The models are from the {picamera2} project's TensorFlow example, and are likely subject to their own licenses.
This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], available in the link:LICENSE.adoc[license file].

© 2024 Jordan Williams

== Authors

mailto:{email}[{author}]
