# This config template is tweaked for capturing fast-moving creatures, such as birds.
# Note that without global shutter, there can be distortions in the image when the creature is moving quickly.
# Rolling shutter also makes it more diffult to successfully detect fast-moving objects.
[detectionator]

# Capture several photographs upon a successful detection.
# Re-running the detection algorithm before taking another photograph may lead to a considerable delay before another picture.
burst = 4

# Focus the lens as quickly as possible.
autofocus-speed = "fast"

# Don't use a gap after a successful detection but start searching again immediately.
gap = 0

# Use a lower resolution for faster processing at the cost of being able to detect objects further away.
# The default is 1/8 of the full resolution, 576x324, which is a pretty good for fairly close up, fast-moving objects.
# low-resolution-width = 576
# low-resolution-height = 324

# Below are standard options.
label = "/usr/local/share/detectionator/models/coco_labels.txt"
log-level = "info"
match = ["bird", "bear", "cat", "cow", "dog", "elephant", "giraffe", "horse", "sheep", "zebra"]
model = "/usr/local/share/detectionator/models/mobilenet_v2.tflite"
output = "~/Pictures"
