# This config template is tweaked for capturing fast-moving creatures, such as birds.
# Note that without global shutter, there can be distortions in the image when the creature is moving quickly.
# Rolling shutter also makes it more diffult to successfully detect fast-moving objects.
[detectionator]

# Capture several photographs upon a successful detection.
# Re-running the detection algorithm before taking another photograph may lead to a considerable delay before another picture.
burst = 4

# Focus the lens on the closest part of the range.
# todo Test how well the Macro range works.
# autofocus-range = "macro"
autofocus-range = "full"

autofocus-mode = "auto"

# Focus the lens as quickly as possible.
autofocus-speed = "fast"

detection-threshold = 0.4

encoder-quality = "high"

focal-detection-threshold = 0.25

# Don't use a gap after a successful detection but start searching again immediately.
gap = 0

# Shape mobilenet_v2 was trained with.
low-resolution-width = 300
low-resolution-height = 300

# Use a lower resolution for faster processing at the cost of being able to detect objects further away.
# The default is 1/8 of the full resolution, 576x324, which is a pretty good for fairly close up, fast-moving objects.
# Shape Yolov5 s was trained with
#low-resolution-width = 640
#low-resolution-height = 640

# other models use resolution 320x240?
# low-resolution-width = 576
# low-resolution-height = 324

# Below are standard options.
#label = "/usr/local/share/detectionator/models/coco_labels_yolov5.txt"
label = "/usr/local/share/detectionator/models/coco_labels.txt"
log-level = "info"
match = ["bird", "bear", "cat", "cow", "dog", "elephant", "giraffe", "horse", "sheep", "zebra"]
#model = "/usr/local/share/detectionator/models/yolov5s-fp16.tflite"
model = "/usr/local/share/detectionator/models/mobilenet_v2.tflite"
output = "~/Pictures"
